### ISSUE TITLE
VS2015 SLN and Projects Fail to Open due to Incorrect Property Path

### ISSUE THREAD

**Issue by marselas** [GPUOpen-Tools/GPA#1]
This is incorrect, and causes all the projects to fail to load:
GPA-master\GPUPerfAPI\Build\VS2015\GPA-Common.props(5,9): The imported project "GPA-master\Common\Src\Vsprops\Global-Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The file is actually in:
"GPA-master\GPUPerfAPI\Build\VS2015\GPA-Common.props"

Actually, it looks like most of the *.props referenced are missing instead of just incorrect paths.

**Comment by chesik-amd** [comment]
It sounds like you didn't clone the "Common" submodule.  Can you check if the following steps help to resolve this issue:

From the root GPA directory, run the following four commands:
git submodule init
git submodule update
cd Common
git checkout master

**Comment by marselas** [comment]
I downloaded a zip file of the whole repo

**Comment by marselas** [comment]
It looks like the zip file that is downloaded doesn't match the directory structure of the repo.

I'll retry by sync'ing the depot per your instructions and file a new issue if it's still a problem

thanks!

**Comment by chesik-amd** [comment]
No problem.  I also updated README.md to include the full set of commands required to clone the repo and the submodule
