### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by trinayan** [GPUOpen-Tools/GPA#10]
When I execute build.sh It succeeds up to a point and then fails as seen below. What can be done to resolve this issue?
"
Build GPUPerfAPI-Common, 64-bit...
Build GPUPerfAPI-Common, 32-bit...
Build DeviceInfo, 64-bit...
Build DeviceInfo, 32-bit...
Build GPUPerfAPICounterGenerator, 64-bit...
Failed to build GPUPerfAPICounterGenerator, 64 bit  "

**Comment by tcsekhar** [comment]
I'm getting the same error. Anyone please?

**Comment by chesik-amd** [comment]
The build log file is called GPUPerfAPI_Build.log file.  This file should be in the GPA/Build/Linux directory.

Any compiler errors encountered during the build will be written to that file.  Can you take a look and post the error messages?  That will hopefully help figure out the cause of the build failure.

Thanks,
Chris

**Comment by chesik-amd** [comment]
If this is still an issue in current sources, please reopen, and provide the contents of the build log file.
