### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by PyrekP** [GPUOpen-Tools/GPA#11]
Are there plans for Vulkan support with hardware-based counters or should we just use Radeon GPU-Profiler for traces and hw counters on Vulkan and/or DX12?

**Comment by chesik-amd** [comment]
Yes, there are plans to release a version of GPA for both DX12 and Vulkan with hardware counter support.  We are actively working on it and hope to release it soon.

Chris

**Comment by chesik-amd** [comment]
GPUPerfAPI 3.0, which has just been released has support for both Vulkan and DX12
