### ISSUE TITLE
Runtime crash when HSA_TOOLS_LIB is set outside of GPA.

### ISSUE THREAD

**Issue by cderb** [GPUOpen-Tools/GPA#12]
I'm using GPA in conjunction with some code that is also attempting to wrap the HSA runtime, and setting the HSA_TOOLS_LIB variable in the environment seems to disturb the initialization phase of GPA.

In SetHSAToolsLibEnvVar, the hsa-runtime-tools64 library will be overwritten with the current contents of HSA_TOOLS_LIB if the environment variable is set. This will lead to HSA skipping the OnLoad function for this library and most likely result in a segfault later when one of the tools lib functions is called. For me this was hsa_ext_tools_set_callback_functions a few levels down into GPA_OpenContext.

I'm fixing this on my end currently by including the hsa tools lib in my variable string, but this should probably be checked in the set tools lib function.

**Comment by chesik-amd** [comment]
Hi.  This should be fixed in GPUPerfAPI 3.0, which has just been released.
