### ISSUE TITLE
GPA seems to be incompatible with Vulkan 1.1.73.0

### ISSUE THREAD

**Issue by igpooh** [GPUOpen-Tools/GPA#18]
I downloaded GPA for Windows and proceeded with installation guided by manual. After UpdateCommon.py script finished the building stage was failed for GPUPerfAPIVK due to struct redefinition.
The error is:

1>VkGPAImplementor.cpp
1>c:\users\igazizov\downloads\gpa\common\src\amdvkext\vk_amd_shader_core_properties.h(45): error C2011: 'VkPhysicalDeviceShaderCorePropertiesAMD': 'struct' type redefinition
1>c:\vulkansdk\1.1.73.0\include\vulkan\vulkan_core.h(7416): note: see declaration of 'VkPhysicalDeviceShaderCorePropertiesAMD'
1>c:\users\igazizov\downloads\gpa\gpa-master\src\gpuperfapivk\vkgpaimplementor.cpp(56): error C2079: 'shaderCorePropertiesAMD' uses undefined struct 'VkPhysicalDeviceShaderCorePropertiesAMD'

As it turned out, VkPhysicalDeviceShaderCorePropertiesAMD structure in vk_amd_shader_core_properties.h is the same as in vulkan_core.h. That is why the error is present.

I commented out the structure in vk_amd_shader_core_properties.h and managed to build the project. The issue might be in the difference between new and old versions of Vulkan API. I am submitting the issue just to confirm this assumption.

Thank you in advance,
Ilias

**Comment by chesik-amd** [comment]
Thanks for this report.  We used 1.0.68.0 for the current release.  We will look into making things compatible with newer versions of Vulkan.

**Comment by chesik-amd** [comment]
This should be fixed in GPA 3.2
