### ISSUE TITLE
Sub-workload counter granularity

### ISSUE THREAD

**Issue by msiglreith** [GPUOpen-Tools/GPA#30]
Hi, first of all thanks for publishing this library!

Looking trough the API I'm wondering if there is the possibility to sample workloads on a smaller granularity? If I understand it correctlt, it's currently only possible to get samples per draw/dispatch call for example but not possible to get information about the individual wavefronts in a similiar fashion and granularity as the Radeon GPU profiler (wavefront occupancy)?

Cheers

**Comment by jlgreathouse** [comment]
Hi @msiglreith 

The current performance counter architecture of AMD GPUs does not allow performance counter monitoring of individual wavefronts. RGP uses a different performance monitoring mechanism inside AMD GPUs that is not the same as normal performance counters. GPA is, I believe, designed specifically for gathering performance counters.

**Comment by msiglreith** [comment]
@jlgreathouse thanks for the response!
I assume there isn't public information (API) regarding the performance monitoring used by RGP, is it?

**Comment by jlgreathouse** [comment]
Unfortunately, no, not at this time.
