### ISSUE TITLE
Clarification of Vulkan Example

### ISSUE THREAD

**Issue by chaoticbob** [GPUOpen-Tools/GPA#35]
Can additional clarification be provided for:
https://github.com/GPUOpen-Tools/GPA/blob/master/Src/Examples/Vulkan/VkColorCube/vkcolorcube.cpp#L1869-L1905

Based on the comments the first for loop only seems to apply when GPA is not loaded. If that's the case, shouldn't it belong in an else caluse? Additionally maybe the two IsLoaded() blocks could be merged since there's doesn't seem to be a logical reason why they're separated.

**Comment by chesik-amd** [comment]
The command buffers built in the first for loop are also used to continue rendering after all counters have been collected.  See the else clause here: https://github.com/GPUOpen-Tools/GPA/blob/master/Src/Examples/Vulkan/VkColorCube/vkcolorcube.cpp#L1869-L1905

Yes, it does look like the two IsLoaded blocks can be merged. We'll take a look at doing this for the next GPA release.

Thanks for the feedback

**Comment by chaoticbob** [comment]
Thanks!
