### ISSUE TITLE
Resetting sessions possible?

### ISSUE THREAD

**Issue by chaoticbob** [GPUOpen-Tools/GPA#37]
Is it possible to reset a session or is it by design that this is not possible? Looking through the code, the state of a session does not ever return to GPA_SESSION_STATE_NOT_STARTED once it leaves it. 

This implies that a session object cannot be reused and requires create/delete for every sample. Just looking to verify the behavior.

**Comment by chesik-amd** [comment]
Yes, your observation is correct: the current implementation does not support resetting a session.

**Comment by chaoticbob** [comment]
Thanks for the confirmation!
