### ISSUE TITLE
Does GPA_IsSessionComplete really need to issue an error?

### ISSUE THREAD

**Issue by chaoticbob** [GPUOpen-Tools/GPA#38]
It seems like when capturing, one might want to use GPA_IsSessionComplete to determine if the results are ready. Is it really necessary for every call to GPA_IsSessionComplete to log "Session has not been started" error?

**Comment by chesik-amd** [comment]
Do you have a valid reson for calling GPA_IsSessionComplete before starting the session with GPA_BeginSession?

**Comment by chaoticbob** [comment]
I do not. Sorry, I should have been more specific. I was just really after whether one can call GPA_IsSessionComplete before session begin. Which it looks like you can't. Thanks.
