### ISSUE TITLE
Why are are all counters FLOAT64?

### ISSUE THREAD

**Issue by chaoticbob** [GPUOpen-Tools/GPA#39]
Vulkan:
https://github.com/GPUOpen-Tools/GPA/blob/master/Src/GPUPerfAPICounterGenerator/PublicCounterDefsVKGfx9.cpp#L13

DX12:
https://github.com/GPUOpen-Tools/GPA/blob/master/Src/GPUPerfAPICounterGenerator/PublicCounterDefsVKGfx9.cpp#L13

Definitions:
https://github.com/GPUOpen-Tools/GPA/blob/master/Src/PublicCounterCompilerInputFiles/PublicCounterDefinitionsGfx9.txt

**Comment by chesik-amd** [comment]
I don't really have a good answer here other than to say "for historical reasons".  It's just always been that way.  For now, it's best to treat them all as float even the ones where it doesn't make sense to have a fractional count.

This is something we may change in the future but for now, this is the way it is.

**Comment by chaoticbob** [comment]
Is it safe to cast some of the values back to UINT64 simply for display purposes based on the USAGE?

**Comment by chesik-amd** [comment]
Yes, that should be safe. If you run into problems with this, please let us know.

**Comment by chaoticbob** [comment]
Thanks!
