### ISSUE TITLE
Fresh pull, Common updated, build failed: could not open include files

### ISSUE THREAD

**Issue by lawrencem99** [GPUOpen-Tools/GPA#5]
I hate to be "that guy" but I would have thought following the readme would result in an operational build.

Build output:

1>------ Build started: Project: GPUPerfAPIDX, Configuration: Debug x64 ------
2>------ Skipped Build: Project: Documentation, Configuration: Debug Win32 ------
2>Project not selected to build for this solution configuration 
3>------ Build started: Project: GPUPerfAPICounterGenerator, Configuration: Debug x64 ------
1>  DXUtils.cpp
3>  GPACounterGeneratorBase.cpp
1>c:\users\god\workspace\ext\gpa-master\src\gpuperfapidx\dxUtils.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGeneratorCommon.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPACounterGeneratorCommon.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGeneratorDX11.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGeneratorDX11Base.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGeneratorDX11NonAMD.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGeneratorDX12.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGeneratorGL.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGeneratorHSA.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGeneratorSchedulerManager.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPACounterGeneratorSchedulerManager.h(16): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterSchedulerBase.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAICounterAccessor.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterSchedulerCL.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAICounterAccessor.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterSchedulerDX11.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterSchedulerDX12.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAICounterAccessor.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterSchedulerGL.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAICounterAccessor.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterSchedulerHSA.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAICounterAccessor.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPAInternalCountersFiji.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPAInternalCountersGfx6.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPAPublicCounters.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  GPASplitCountersConsolidatedDX12.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  GPASwCounterManager.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  Generating Code...
3>  Compiling...
3>  InternalCountersCLGfx6.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersCLGfx7.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersCLGfx8.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersDX11Gfx6.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersDX11Gfx7.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersDX11Gfx8.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersGLGfx6.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersGLGfx7.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersGLGfx8.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersHSAGfx7.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  InternalCountersHSAGfx8.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  PublicCounterDefsCLGfx6.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  PublicCounterDefsCLGfx7.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  PublicCounterDefsCLGfx8.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  GPACounterGeneratorCL.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAInternalCounter.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  GPACounterGenerator.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAICounterAccessor.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
3>  PublicCounterDefsDX11Gfx6.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  PublicCounterDefsDX11Gfx7.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  PublicCounterDefsDX11Gfx8.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  PublicCounterDefsGLGfx6.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  Generating Code...
3>  Compiling...
3>  PublicCounterDefsGLGfx7.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  PublicCounterDefsGLGfx8.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  PublicCounterDefsHSAGfx7.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  PublicCounterDefsHSAGfx8.cpp
3>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAPublicCounters.h(12): fatal error C1083: Cannot open include file: 'GPUPerfAPIOS.h': No such file or directory
3>  Generating Code...
4>------ Build started: Project: GPUPerfAPICounters, Configuration: Debug x64 ------
5>------ Build started: Project: GPUPerfAPIGL, Configuration: Debug x64 ------
6>------ Build started: Project: GPUPerfAPIGLES, Configuration: Debug x64 ------
7>------ Build started: Project: GPUPerfAPICL, Configuration: Debug x64 ------
5>  GLPerfMonitorCache.cpp
4>  GPUPerfAPICounters.cpp
4>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicountergenerator\GPAICounterAccessor.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
8>------ Build started: Project: GPUPerfAPIUnitTests, Configuration: Debug x64 ------
6>  GLPerfMonitorCache.cpp
7>  CLPerfCounterAMDExtension.cpp
7>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicl\CLRTModuleLoader.h(12): fatal error C1083: Cannot open include file: 'APIRTModuleLoader.h': No such file or directory
7>  CLPerfCounterBlock.cpp
8>LINK : fatal error LNK1104: cannot open file 'C:\Users\god\Workspace\Ext\GPA-master\Output\Debug\bin\GPUPerfAPICounterGenerator-x64-d.lib'
9>------ Build started: Project: GPUPerfAPIDX12, Configuration: Debug x64 ------
5>..\..\Src\GPUPerfAPIGL\GLPerfMonitorCache.cpp(10): fatal error C1083: Cannot open include file: 'Logging.h': No such file or directory
5>  GPUPerfAPIGL.cpp
7>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicl\CLRTModuleLoader.h(12): fatal error C1083: Cannot open include file: 'APIRTModuleLoader.h': No such file or directory
7>  GPUPerfAPICL.cpp
5>c:\users\god\workspace\ext\gpa-master\src\gpuperfapigl\../GPUPerfAPICounterGenerator/GPACounterGenerator.h(14): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
5>  Generating Code...
7>c:\users\god\workspace\ext\gpa-master\src\gpuperfapicl\../GPUPerfAPICounterGenerator/GPACounterGenerator.h(14): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
7>  Generating Code...
6>..\..\Src\GPUPerfAPIGL\GLPerfMonitorCache.cpp(10): fatal error C1083: Cannot open include file: 'Logging.h': No such file or directory
9>  DX12CommandListSwQueries.cpp
6>  GPUPerfAPIGL.cpp
9>..\..\Src\GPUPerfAPIDX12\DX12CommandListSwQueries.cpp(8): fatal error C1083: Cannot open include file: 'Logging.h': No such file or directory
6>c:\users\god\workspace\ext\gpa-master\src\gpuperfapigl\../GPUPerfAPICounterGenerator/GPACounterGenerator.h(14): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
9>  DX12CommandListSWQueryGroup.cpp
6>  Generating Code...
9>c:\users\god\workspace\ext\gpa-master\src\gpuperfapidx12\DX12CommandListSWQueryGroup.h(11): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
9>  DX12CounterDataRequestProxy.cpp
9>c:\users\god\workspace\ext\gpa-master\src\gpuperfapidx12\DX12DataRequest.h(11): fatal error C1083: Cannot open include file: 'GPADataRequest.h': No such file or directory
9>  DX12DataRequest.cpp
9>c:\users\god\workspace\ext\gpa-master\src\gpuperfapidx12\DX12DataRequest.h(11): fatal error C1083: Cannot open include file: 'GPADataRequest.h': No such file or directory
9>  DX12SoftwareCounterDataRequest.cpp
9>c:\users\god\workspace\ext\gpa-master\src\gpuperfapidx12\DX12DataRequest.h(11): fatal error C1083: Cannot open include file: 'GPADataRequest.h': No such file or directory
9>  DX12Utils.cpp
9>c:\users\god\workspace\ext\gpa-master\src\gpuperfapidx12\DX12Utils.h(13): fatal error C1083: Cannot open include file: 'GPUPerfAPITypes.h': No such file or directory
9>  GPAContextStateDX12.cpp
9>c:\users\god\workspace\ext\gpa-master\src\gpuperfapidx12\GPAContextStateDX12.h(17): fatal error C1083: Cannot open include file: 'GPAContextState.h': No such file or directory
9>  GPUPerfAPIDX12.cpp
9>..\..\Src\GPUPerfAPIDX12\GPUPerfAPIDX12.cpp(11): fatal error C1083: Cannot open include file: 'GPUPerfAPIImp.h': No such file or directory
9>  Generating Code...
========== Build: 0 succeeded, 8 failed, 2 up-to-date, 1 skipped ==========

**Comment by chesik-amd** [comment]
Looks like this is caused by your GPA root directory being called "gpa-master" rather than "gpa".  For now, if you rename the "gpa-master" dir to "gpa" does it work?

**Comment by lawrencem99** [comment]
Yes, it does! Thank you. Would a little note in the readme, about downloading the source via zip be appropriate?
