### ISSUE TITLE
ABI Incompatible Use of Bool

### ISSUE THREAD

**Issue by ajguillon** [GPUOpen-Tools/GPA#7]
Hi,

I noticed that within GPUPerfAPITypes.h the following code appears:

`    #ifndef __cplusplus
        typedef gpa_uint8 bool;
    #endif
`

I am concerned that this will introduce a differently sized type between C and C++, and will therefore introduce ABI issues into the shared library.  In my opinion, the bool type should not be used anywhere that ABI must be maintained, so it would be best if this was fixed to be an integer type only.

**Comment by chesik-amd** [comment]
This should no longer be an issue in GPUPerfAPI 3.0, which has just been released
